// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id$
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Portions Copyright (C) 1998-2000 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// $Log$
// Revision 1.4  2003/03/15 20:07:12  smite-meister
// Initial Hexen compatibility!
//
// Revision 1.3  2003/02/16 16:54:49  smite-meister
// L2 sound cache done
//
// Revision 1.2  2003/01/25 21:33:05  smite-meister
// Now compiles with MinGW 2.0 / GCC 3.2.
// Builder can choose between dynamic and static linkage.
//
// Revision 1.1.1.1  2002/11/16 14:17:48  hurdler
// Initial C++ version of Doom Legacy
//
//
// DESCRIPTION:
//      music/sound tables, and related sound routines
//
// Note: the tables were originally created by a sound utility at Id,
//       kept as a sample, DOOM2 sounds.
//
//-----------------------------------------------------------------------------


#include "doomtype.h"
#include "i_sound.h"
#include "sounds.h"
#include "r_defs.h"
#include "r_things.h"
#include "r_sprite.h" // skins
#include "z_zone.h"
#include "w_wad.h"


// Doom/Heretic music names corresponding to musicenum_t
// NOTE: padded with \0 to stringlen=8, to allow dehacked patching

char* MusicNames[NUMMUSIC] =
{
    { NULL },
    // Doom
    { "D_E1M1\0\0" },
    { "D_E1M2\0\0" },
    { "D_E1M3\0\0" },
    { "D_E1M4\0\0" },
    { "D_E1M5\0\0" },
    { "D_E1M6\0\0" },
    { "D_E1M7\0\0" },
    { "D_E1M8\0\0" },
    { "D_E1M9\0\0" },

    { "D_E2M1\0\0" },
    { "D_E2M2\0\0" },
    { "D_E2M3\0\0" },
    { "D_E2M4\0\0" },
    { "D_E2M5\0\0" },
    { "D_E2M6\0\0" },
    { "D_E2M7\0\0" },
    { "D_E2M8\0\0" },
    { "D_E2M9\0\0" },

    { "D_E3M1\0\0" },
    { "D_E3M2\0\0" },
    { "D_E3M3\0\0" },
    { "D_E3M4\0\0" },
    { "D_E3M5\0\0" },
    { "D_E3M6\0\0" },
    { "D_E3M7\0\0" },
    { "D_E3M8\0\0" },
    { "D_E3M9\0\0" },
    // Ultimate Doom Ep. 4 re-used music
    { "D_E3M4\0\0" },
    { "D_E3M2\0\0" },
    { "D_E3M3\0\0" },
    { "D_E1M5\0\0" },
    { "D_E2M7\0\0" },
    { "D_E2M4\0\0" },
    { "D_E2M6\0\0" },
    { "D_E2M5\0\0" },
    { "D_E1M9\0\0" },

    { "D_INTER\0"  },
    { "D_INTRO\0"  },
    { "D_BUNNY\0"  },
    { "D_VICTOR"   },
    { "D_INTROA"   },
    // Doom II
    { "D_RUNNIN"   },
    { "D_STALKS"   },
    { "D_COUNTD"   },
    { "D_BETWEE"   },
    { "D_DOOM\0\0" },
    { "D_THE_DA"   },
    { "D_SHAWN\0"  },
    { "D_DDTBLU"   },
    { "D_IN_CIT"   },
    { "D_DEAD\0\0" },
    { "D_STLKS2"   },
    { "D_THEDA2"   },
    { "D_DOOM2\0"  },
    { "D_DDTBL2"   },
    { "D_RUNNI2"   },
    { "D_DEAD2\0"  },
    { "D_STLKS3"   },
    { "D_ROMERO"   },
    { "D_SHAWN2"   },
    { "D_MESSAG"   },
    { "D_COUNT2"   },
    { "D_DDTBL3"   },
    { "D_AMPIE\0"  },
    { "D_THEDA3"   },
    { "D_ADRIAN"   },
    { "D_MESSG2"   },
    { "D_ROMER2"   },
    { "D_TENSE\0"  },
    { "D_SHAWN3"   },
    { "D_OPENIN"   },
    { "D_EVIL\0\0" },
    { "D_ULTIMA"   },
    { "D_READ_M"   },
    { "D_DM2TTL"   },
    { "D_DM2INT"   },
    // Heretic
    { "MUS_E1M1" }, // 1-1
    { "MUS_E1M2" },
    { "MUS_E1M3" },
    { "MUS_E1M4" },
    { "MUS_E1M5" },
    { "MUS_E1M6" },
    { "MUS_E1M7" },
    { "MUS_E1M8" },
    { "MUS_E1M9" },

    { "MUS_E2M1" }, // 2-1
    { "MUS_E2M2" },
    { "MUS_E2M3" },
    { "MUS_E2M4" },
    { "MUS_E1M4" },
    { "MUS_E2M6" },
    { "MUS_E2M7" },
    { "MUS_E2M8" },
    { "MUS_E2M9" },

    { "MUS_E1M1" }, // 3-1
    { "MUS_E3M2" },
    { "MUS_E3M3" },
    { "MUS_E1M6" },
    { "MUS_E1M3" },
    { "MUS_E1M2" },
    { "MUS_E1M5" },
    { "MUS_E1M9" },
    { "MUS_E2M6" },

    { "MUS_E1M6" }, // 4-1
    { "MUS_E1M2" },
    { "MUS_E1M3" },
    { "MUS_E1M4" },
    { "MUS_E1M5" },
    { "MUS_E1M1" },
    { "MUS_E1M7" },
    { "MUS_E1M8" },
    { "MUS_E1M9" },

    { "MUS_E2M1" }, // 5-1
    { "MUS_E2M2" },
    { "MUS_E2M3" },
    { "MUS_E2M4" },
    { "MUS_E1M4" },
    { "MUS_E2M6" },
    { "MUS_E2M7" },
    { "MUS_E2M8" },
    { "MUS_E2M9" },

    { "MUS_E3M2" }, // 6-1
    { "MUS_E3M3" }, // 6-2
    { "MUS_E1M6" }, // 6-3

    { "MUS_TITL" },
    { "MUS_INTR" },
    { "MUS_CPTD" }
};


//
// Information about all the sfx
//

sfxinfo_t S_sfx[NUMSFX] =
{
  // S_sfx[0] needs to be a dummy for odd reasons.
//             singularity(U)        
//   tagname              |   priority(U)
//     |    lumpname      |       |
  { NULL, "none"       , false,   0},

  { NULL, "dspistol"   , false,  64},
  { NULL, "dsshotgn"   , false,  64},
  { NULL, "dssgcock"   , false,  64},
  { NULL, "dsdshtgn"   , false,  64},
  { NULL, "dsdbopn\0"  , false,  64},
  { NULL, "dsdbcls\0"  , false,  64},
  { NULL, "dsdbload"   , false,  64},
  { NULL, "dsplasma"   , false,  64},
  { NULL, "dsbfg\0\0\0", false,  64},
  { NULL, "dssawup\0"  , false,  64},
  { NULL, "dssawidl"   , false, 118},
  { NULL, "dssawful"   , false,  64},
  { NULL, "dssawhit"   , false,  64},
  { NULL, "dsrlaunc"   , false,  64},
  { NULL, "dsrxplod"   , false,  70},
  { NULL, "dsfirsht"   , false,  70},
  { NULL, "dsfirxpl"   , false,  70},
  { NULL, "dspstart"   , false, 100},
  { NULL, "dspstop\0"  , false, 100},
  { NULL, "dsdoropn"   , false, 100},
  { NULL, "dsdorcls"   , false, 100},
  { NULL, "dsstnmov"   , false, 119},
  { NULL, "dsswtchn"   , false,  78},
  { NULL, "dsswtchx"   , false,  78},
  { NULL, "dsplpain"   , false,  96},   //SKSPLPAIN},
  { NULL, "dsdmpain"   , false,  96},
  { NULL, "dspopain"   , false,  96},
  { NULL, "dsvipain"   , false,  96},
  { NULL, "dsmnpain"   , false,  96},
  { NULL, "dspepain"   , false,  96},
  { NULL, "dsslop\0\0" , false,  78},    //SKSSLOP},
  { NULL, "dsitemup"   ,  true,  78},
  { NULL, "dswpnup"    ,  true,  78},
  { NULL, "dsoof\0\0\0", false,  96},    //SKSOOF},
  { NULL, "dstelept"   , false,  32},
  { NULL, "dsposit1"   ,  true,  98},
  { NULL, "dsposit2"   ,  true,  98},
  { NULL, "dsposit3"   ,  true,  98},
  { NULL, "dsbgsit1"   ,  true,  98},
  { NULL, "dsbgsit2"   ,  true,  98},
  { NULL, "dssgtsit"   ,  true,  98},
  { NULL, "dscacsit"   ,  true,  98},
  { NULL, "dsbrssit"   ,  true,  94},
  { NULL, "dscybsit"   ,  true,  92},
  { NULL, "dsspisit"   ,  true,  90},
  { NULL, "dsbspsit"   ,  true,  90},
  { NULL, "dskntsit"   ,  true,  90},
  { NULL, "dsvilsit"   ,  true,  90},
  { NULL, "dsmansit"   ,  true,  90},
  { NULL, "dspesit\0"  ,  true,  90},
  { NULL, "dssklatk"   , false,  70},
  { NULL, "dssgtatk"   , false,  70},
  { NULL, "dsskepch"   , false,  70},
  { NULL, "dsvilatk"   , false,  70},
  { NULL, "dsclaw\0\0" , false,  70},
  { NULL, "dsskeswg"   , false,  70},
  { NULL, "dspldeth"   , false,  32}, //SKSPLDETH},
  { NULL, "dspdiehi"   , false,  32}, //SKSPDIEHI},
  { NULL, "dspodth1"   , false,  70},
  { NULL, "dspodth2"   , false,  70},
  { NULL, "dspodth3"   , false,  70},
  { NULL, "dsbgdth1"   , false,  70},
  { NULL, "dsbgdth2"   , false,  70},
  { NULL, "dssgtdth"   , false,  70},
  { NULL, "dscacdth"   , false,  70},
  { NULL, "dsskldth"   , false,  70},
  { NULL, "dsbrsdth"   , false,  32},
  { NULL, "dscybdth"   , false,  32},
  { NULL, "dsspidth"   , false,  32},
  { NULL, "dsbspdth"   , false,  32},
  { NULL, "dsvildth"   , false,  32},
  { NULL, "dskntdth"   , false,  32},
  { NULL, "dspedth\0"  , false,  32},
  { NULL, "dsskedth"   , false,  32},
  { NULL, "dsposact"   ,  true, 120},
  { NULL, "dsbgact\0"  ,  true, 120},
  { NULL, "dsdmact\0"  ,  true, 120},
  { NULL, "dsbspact"   ,  true, 100},
  { NULL, "dsbspwlk"   ,  true, 100},
  { NULL, "dsvilact"   ,  true, 100},
  { NULL, "dsnoway\0"  , false,  78}, //SKSNOWAY},
  { NULL, "dsbarexp"   , false,  60},
  { NULL, "dspunch\0"  , false,  64}, //SKSPUNCH},
  { NULL, "dshoof\0\0" , false,  70},
  { NULL, "dsmetal\0"  , false,  70},
  { NULL, "dspistol"  , false,  64}, // FIXME wrong pitch for chaingun... "dschgun\0", &S_sfx[sfx_pistol], 150, 0},
  { NULL, "dstink\0\0" , false,  60},
  { NULL, "dsbdopn\0"  , false, 100},
  { NULL, "dsbdcls\0"  , false, 100},
  { NULL, "dsitmbk\0"  , false, 100},
  { NULL, "dsflame\0"  , false,  32},
  { NULL, "dsflamst"   , false,  32},
  { NULL, "dsgetpow"   , false,  60},
  { NULL, "dsbospit"   , false,  70},
  { NULL, "dsboscub"   , false,  70},
  { NULL, "dsbossit"   , false,  70},
  { NULL, "dsbospn\0"  , false,  70},
  { NULL, "dsbosdth"   , false,  70},
  { NULL, "dsmanatk"   , false,  70},
  { NULL, "dsmandth"   , false,  70},
  { NULL, "dssssit\0"  , false,  70},
  { NULL, "dsssdth\0"  , false,  70},
  { NULL, "dskeenpn"   , false,  70},
  { NULL, "dskeendt"   , false,  70},
  { NULL, "dsskeact"   , false,  70},
  { NULL, "dsskesit"   , false,  70},
  { NULL, "dsskeatk"   , false,  70},
  { NULL, "dsradio\0"  , false,  60}, //SKSRADIO},

  // legacy.wad extra sounds
  // sound when the player avatar jumps in air 'hmpf!'
  { NULL, "dsjump\0\0" , false,  60}, //SKSJUMP},
  { NULL, "dsouch\0\0" , false,  64}, //SKSOUCH},
  // water sounds
  { NULL, "dsgloop\0"  , false,  60},
  { NULL, "dssplash"   , false,  64},
  { NULL, "dsfloush"   , false,  64},

  // Heretic
  { NULL, "gldhit",  false, 32},
  { NULL, "gntful",  false, 32},
  { NULL, "gnthit",  false, 32},
  { NULL, "gntpow",  false, 32},
  { NULL, "gntact",  false, 32},
  { NULL, "gntuse",  false, 32},
  { NULL, "phosht",  false, 32},
  { NULL, "phohit",  false, 32},
  { NULL, "hedat1", false, 32}, // "-phopow", &S_sfx[sfx_hedat1], -1, -1},
  { NULL, "lobsht",  false, 20},
  { NULL, "lobhit",  false, 20},
  { NULL, "lobpow",  false, 20},
  { NULL, "hrnsht",  false, 32},
  { NULL, "hrnhit",  false, 32},
  { NULL, "hrnpow",  false, 32},
  { NULL, "ramphit", false, 32},
  { NULL, "ramrain", false, 10},
  { NULL, "bowsht",  false, 32},
  { NULL, "stfhit",  false, 32},
  { NULL, "stfpow",  false, 32},
  { NULL, "stfcrk",  false, 32},
  { NULL, "impsit",  false, 32},
  { NULL, "impat1",  false, 32},
  { NULL, "impat2",  false, 32},
  { NULL, "impdth",  false, 80},
  { NULL, "impsit", false, 20}, //"-impact", &S_sfx[sfx_impsit], -1, -1},
  { NULL, "imppai",  false, 32},
  { NULL, "mumsit",  false, 32},
  { NULL, "mumat1",  false, 32},
  { NULL, "mumat2",  false, 32},
  { NULL, "mumdth",  false, 80},
  { NULL, "mumsit", false, 20}, //"-mumact" &S_sfx[sfx_mumsit], -1, -1},
  { NULL, "mumpai",  false, 32},
  { NULL, "mumhed",  false, 32},
  { NULL, "bstsit",  false, 32},
  { NULL, "bstatk",  false, 32},
  { NULL, "bstdth",  false, 80},
  { NULL, "bstact",  false, 20},
  { NULL, "bstpai",  false, 32},
  { NULL, "clksit",  false, 32},
  { NULL, "clkatk",  false, 32},
  { NULL, "clkdth",  false, 80},
  { NULL, "clkact",  false, 20},
  { NULL, "clkpai",  false, 32},
  { NULL, "snksit",  false, 32},
  { NULL, "snkatk",  false, 32},
  { NULL, "snkdth",  false, 80},
  { NULL, "snkact",  false, 20},
  { NULL, "snkpai",  false, 32},
  { NULL, "kgtsit",  false, 32},
  { NULL, "kgtatk",  false, 32},
  { NULL, "kgtat2",  false, 32},
  { NULL, "kgtdth",  false, 80},
  { NULL, "kgtsit", false, 20}, // "-kgtact", &S_sfx[sfx_kgtsit], -1, -1},
  { NULL, "kgtpai",  false, 32},
  { NULL, "wizsit",  false, 32},
  { NULL, "wizatk",  false, 32},
  { NULL, "wizdth",  false, 80},
  { NULL, "wizact",  false, 20},
  { NULL, "wizpai",  false, 32},
  { NULL, "minsit",  false, 32},
  { NULL, "minat1",  false, 32},
  { NULL, "minat2",  false, 32},
  { NULL, "minat3",  false, 32},
  { NULL, "mindth",  false, 80},
  { NULL, "minact",  false, 20},
  { NULL, "minpai",  false, 32},
  { NULL, "hedsit",  false, 32},
  { NULL, "hedat1",  false, 32},
  { NULL, "hedat2",  false, 32},
  { NULL, "hedat3",  false, 32},
  { NULL, "heddth",  false, 80},
  { NULL, "hedact",  false, 20},
  { NULL, "hedpai",  false, 32},
  { NULL, "sorzap",  false, 32},
  { NULL, "sorrise", false, 32},
  { NULL, "sorsit",  false, 200},
  { NULL, "soratk",  false, 32},
  { NULL, "soract",  false, 200},
  { NULL, "sorpai",  false, 200},
  { NULL, "sordsph", false, 200},
  { NULL, "sordexp", false, 200},
  { NULL, "sordbon", false, 200},
  { NULL, "bstsit", false, 32}, // "-sbtsit", &S_sfx[sfx_bstsit], -1, -1},
  { NULL, "bstatk", false, 32}, // "-sbtatk", &S_sfx[sfx_bstatk], -1, -1},
  { NULL, "sbtdth",  false, 80},
  { NULL, "sbtact",  false, 20},
  { NULL, "sbtpai",  false, 32},
  { NULL, "plroof",  false, 32},
  { NULL, "plrpai",  false, 32},
  { NULL, "plrdth",  false, 80},
  { NULL, "gibdth",  false, 100},
  { NULL, "plrwdth", false, 80},
  { NULL, "plrcdth", false, 100},
  { NULL, "itemup",  false, 32},
  { NULL, "wpnup",   false, 32},
  { NULL, "telept",  false, 50},
  { NULL, "doropn",  false, 40},
  { NULL, "dorcls",  false, 40},
  { NULL, "dormov",  false, 40},
  { NULL, "artiup",  false, 32},
  { NULL, "switch",  false, 40},
  { NULL, "pstart",  false, 40},
  { NULL, "pstop",   false, 40},
  { NULL, "stnmov",  false, 40},
  { NULL, "chicpai", false, 32},
  { NULL, "chicatk", false, 32},
  { NULL, "chicdth", false, 40},
  { NULL, "chicact", false, 32},
  { NULL, "chicpk1", false, 32},
  { NULL, "chicpk2", false, 32},
  { NULL, "chicpk3", false, 32},
  { NULL, "keyup"  , false, 50},
  { NULL, "ripslop", false, 16},
  { NULL, "newpod" , false, 16},
  { NULL, "podexp" , false, 40},
  { NULL, "bounce" , false, 16},
  { NULL, "bstatk", false, 16}, // "-volsht", &S_sfx[sfx_bstatk], -1, -1},
  { NULL, "lobhit", false, 16}, // "-volhit", &S_sfx[sfx_lobhit], -1, -1},
  { NULL, "burn"   , false, 10},
  { NULL, "splash" , false, 10},
  { NULL, "gloop"  , false, 10},
  { NULL, "respawn", false, 10},
  { NULL, "blssht" , false, 32},
  { NULL, "blshit" , false, 32},
  { NULL, "chat"   , false, 100},
  { NULL, "artiuse", false, 32},
  { NULL, "gfrag"  , false, 100},
  { NULL, "waterfl", false, 16},

  // Monophonic sounds
  { NULL, "wind"   , false, 16},
  { NULL, "amb1"   , false,  1},
  { NULL, "amb2"   , false,  1},
  { NULL, "amb3"   , false,  1},
  { NULL, "amb4"   , false,  1},
  { NULL, "amb5"   , false,  1},
  { NULL, "amb6"   , false,  1},
  { NULL, "amb7"   , false,  1},
  { NULL, "amb8"   , false,  1},
  { NULL, "amb9"   , false,  1},
  { NULL, "amb10"  , false,  1},
  { NULL, "amb11"  , false,  1},


  // Hexen
  // tagname, lumpname, priority
  { "PlayerFighterNormalDeath", NULL, false, 256},
  { "PlayerFighterCrazyDeath", NULL, false, 256},
  { "PlayerFighterExtreme1Death", NULL, false, 256},
  { "PlayerFighterExtreme2Death", NULL, false, 256},
  { "PlayerFighterExtreme3Death", NULL, false, 256},
  { "PlayerFighterBurnDeath", NULL, false, 256},
  { "PlayerClericNormalDeath", NULL, false, 256},
  { "PlayerClericCrazyDeath", NULL, false, 256},
  { "PlayerClericExtreme1Death", NULL, false, 256},
  { "PlayerClericExtreme2Death", NULL, false, 256},
  { "PlayerClericExtreme3Death", NULL, false, 256},
  { "PlayerClericBurnDeath", NULL, false, 256},
  { "PlayerMageNormalDeath", NULL, false, 256},
  { "PlayerMageCrazyDeath", NULL, false, 256},
  { "PlayerMageExtreme1Death", NULL, false, 256},
  { "PlayerMageExtreme2Death", NULL, false, 256},
  { "PlayerMageExtreme3Death", NULL, false, 256},
  { "PlayerMageBurnDeath", NULL, false, 256},
  { "PlayerFighterPain", NULL, false, 256},
  { "PlayerClericPain", NULL, false, 256},
  { "PlayerMagePain", NULL, false, 256},
  { "PlayerFighterGrunt", NULL, false, 256},
  { "PlayerClericGrunt", NULL, false, 256},
  { "PlayerMageGrunt", NULL, false, 256},
  { "PlayerLand", NULL, false, 32},
  { "PlayerPoisonCough", NULL, false, 256},
  { "PlayerFighterFallingScream", NULL, false, 256},
  { "PlayerClericFallingScream", NULL, false, 256},
  { "PlayerMageFallingScream", NULL, false, 256},
  { "PlayerFallingSplat", NULL, false, 256},
  { "PlayerFighterFailedUse", NULL, false, 256},
  { "PlayerClericFailedUse", NULL, false, 256},
  { "PlayerMageFailedUse", NULL, false, 256},
  { "PlatformStart", NULL, false, 36},
  { "PlatformStartMetal", NULL, false, 36},
  { "PlatformStop", NULL, false, 40},
  { "StoneMove", NULL, false, 32},
  { "MetalMove", NULL, false, 32},
  { "DoorOpen", NULL, false, 36},
  { "DoorLocked", NULL, false, 36},
  { "DoorOpenMetal", NULL, false, 36},
  { "DoorCloseMetal", NULL, false, 36},
  { "DoorCloseLight", NULL, false, 36},
  { "DoorCloseHeavy", NULL, false, 36},
  { "DoorCreak", NULL, false, 36},
  { "PickupWeapon", NULL, false, 36},
  { "PickupArtifact", NULL, false, 36},
  { "PickupKey", NULL, false, 36},
  { "PickupItem", NULL, false, 36},
  { "PickupPiece", NULL, false, 36},
  { "WeaponBuild", NULL, false, 36},
  { "UseArtifact", NULL, false, 36},
  { "BlastRadius", NULL, false, 36},
  { "Teleport", NULL, false, 256},
  { "ThunderCrash", NULL, false, 30},
  { "FighterPunchMiss", NULL, false, 80},
  { "FighterPunchHitThing", NULL, false, 80},
  { "FighterPunchHitWall", NULL, false, 80},
  { "FighterGrunt", NULL, false, 80},
  { "FighterAxeHitThing", NULL, false, 80},
  { "FighterHammerMiss", NULL, false, 80},
  { "FighterHammerHitThing", NULL, false, 80},
  { "FighterHammerHitWall", NULL, false, 80},
  { "FighterHammerContinuous", NULL, false, 32},
  { "FighterHammerExplode", NULL, false, 80},
  { "FighterSwordFire", NULL, false, 80},
  { "FighterSwordExplode", NULL, false, 80},
  { "ClericCStaffFire", NULL, false, 80},
  { "ClericCStaffExplode", NULL, false, 40},
  { "ClericCStaffHitThing", NULL, false, 80},
  { "ClericFlameFire", NULL, false, 80},
  { "ClericFlameExplode", NULL, false, 80},
  { "ClericFlameCircle", NULL, false, 80},
  { "MageWandFire", NULL, false, 80},
  { "MageLightningFire", NULL, false, 80},
  { "MageLightningZap", NULL, false, 32},
  { "MageLightningContinuous", NULL, false, 32},
  { "MageLightningReady", NULL, false, 30},
  { "MageShardsFire",NULL, false, 80},
  { "MageShardsExplode",NULL, false, 36},
  { "MageStaffFire",NULL, false, 80},
  { "MageStaffExplode",NULL, false, 40},
  { "Switch1", NULL, false, 32},
  { "Switch2", NULL, false, 32},
  { "SerpentSight", NULL, false, 32},
  { "SerpentActive", NULL, false, 32},
  { "SerpentPain", NULL, false, 32},
  { "SerpentAttack", NULL, false, 32},
  { "SerpentMeleeHit", NULL, false, 32},
  { "SerpentDeath", NULL, false, 40},
  { "SerpentBirth", NULL, false, 32},
  { "SerpentFXContinuous", NULL, false, 32},
  { "SerpentFXHit", NULL, false, 32},
  { "PotteryExplode", NULL, false, 32},
  { "Drip", NULL, false, 32},
  { "CentaurSight", NULL, false, 32},
  { "CentaurActive", NULL, false, 32},
  { "CentaurPain", NULL, false, 32},
  { "CentaurAttack", NULL, false, 32},
  { "CentaurDeath", NULL, false, 40},
  { "CentaurLeaderAttack", NULL, false, 32},
  { "CentaurMissileExplode", NULL, false, 32},
  { "Wind", NULL, false, 1},
  { "BishopSight", NULL, false, 32},
  { "BishopActive", NULL, false, 32},
  { "BishopPain", NULL, false, 32},
  { "BishopAttack", NULL, false, 32},
  { "BishopDeath", NULL, false, 40},
  { "BishopMissileExplode", NULL, false, 32},
  { "BishopBlur", NULL, false, 32},
  { "DemonSight", NULL, false, 32},
  { "DemonActive", NULL, false, 32},
  { "DemonPain", NULL, false, 32},
  { "DemonAttack", NULL, false, 32},
  { "DemonMissileFire", NULL, false, 32},
  { "DemonMissileExplode", NULL, false, 32},
  { "DemonDeath", NULL, false, 40},
  { "WraithSight", NULL, false, 32},
  { "WraithActive", NULL, false, 32},
  { "WraithPain", NULL, false, 32},
  { "WraithAttack", NULL, false, 32},
  { "WraithMissileFire", NULL, false, 32},
  { "WraithMissileExplode", NULL, false, 32},
  { "WraithDeath", NULL, false, 40},
  { "PigActive1", NULL, false, 32},
  { "PigActive2", NULL, false, 32},
  { "PigPain", NULL, false, 32},
  { "PigAttack", NULL, false, 32},
  { "PigDeath", NULL, false, 40},
  { "MaulatorSight", NULL, false, 32},
  { "MaulatorActive", NULL, false, 32},
  { "MaulatorPain", NULL, false, 32},
  { "MaulatorHamSwing", NULL, false, 32},
  { "MaulatorHamHit", NULL, false, 32},
  { "MaulatorMissileHit", NULL, false, 32},
  { "MaulatorDeath", NULL, false, 40},
  { "FreezeDeath", NULL, false, 40},
  { "FreezeShatter", NULL, false, 40},
  { "EttinSight", NULL, false, 32},
  { "EttinActive", NULL, false, 32},
  { "EttinPain", NULL, false, 32},
  { "EttinAttack", NULL, false, 32},
  { "EttinDeath", NULL, false, 40},
  { "FireDemonSpawn", NULL, false, 32},
  { "FireDemonActive", NULL, false, 32},
  { "FireDemonPain", NULL, false, 32},
  { "FireDemonAttack", NULL, false, 32},
  { "FireDemonMissileHit", NULL, false, 32},
  { "FireDemonDeath", NULL, false, 40},
  { "IceGuySight", NULL, false, 32},
  { "IceGuyActive", NULL, false, 32},
  { "IceGuyAttack", NULL, false, 32},
  { "IceGuyMissileExplode", NULL, false, 32},
  { "SorcererSight", NULL, false, 256},
  { "SorcererActive", NULL, false, 256},
  { "SorcererPain", NULL, false, 256},
  { "SorcererSpellCast", NULL, false, 256},
  { "SorcererBallWoosh", NULL, false, 256},
  { "SorcererDeathScream", NULL, false, 256},
  { "SorcererBishopSpawn", NULL, false, 80},
  { "SorcererBallPop", NULL, false, 80},
  { "SorcererBallBounce", NULL, false, 80},
  { "SorcererBallExplode", NULL, false, 80},
  { "SorcererBigBallExplode", NULL, false, 80},
  { "SorcererHeadScream", NULL, false, 256},
  { "DragonSight", NULL, false, 64},
  { "DragonActive", NULL, false, 64},
  { "DragonWingflap", NULL, false, 64},
  { "DragonAttack", NULL, false, 64},
  { "DragonPain", NULL, false, 64},
  { "DragonDeath", NULL, false, 64},
  { "DragonFireballExplode", NULL, false, 32},
  { "KoraxSight", NULL, false, 256},
  { "KoraxActive", NULL, false, 256},
  { "KoraxPain", NULL, false, 256},
  { "KoraxAttack", NULL, false, 256},
  { "KoraxCommand", NULL, false, 256},
  { "KoraxDeath", NULL, false, 256},
  { "KoraxStep", NULL, false, 128},
  { "ThrustSpikeRaise", NULL, false, 32},
  { "ThrustSpikeLower", NULL, false, 32},
  { "GlassShatter", NULL, false, 32},
  { "FlechetteBounce", NULL, false, 32},
  { "FlechetteExplode", NULL, false, 32},
  { "LavaMove", NULL, false, 36},
  { "WaterMove", NULL, false, 36},
  { "IceStartMove", NULL, false, 36},
  { "EarthStartMove", NULL, false, 36},
  { "WaterSplash", NULL, false, 32},
  { "LavaSizzle", NULL, false, 32},
  { "SludgeGloop", NULL, false, 32},
  { "HolySymbolFire", NULL, false, 64},
  { "SpiritActive", NULL, false, 32},
  { "SpiritAttack", NULL, false, 32},
  { "SpiritDie", NULL, false, 32},
  { "ValveTurn", NULL, false, 36},
  { "RopePull", NULL, false, 36},
  { "FlyBuzz", NULL, false, 20},
  { "Ignite", NULL, false, 32},
  { "PuzzleSuccess", NULL, false, 256},
  { "PuzzleFailFighter", NULL, false, 256},
  { "PuzzleFailCleric", NULL, false, 256},
  { "PuzzleFailMage", NULL, false, 256},
  { "Earthquake", NULL, false, 32},
  { "BellRing", NULL, false, 32},
  { "TreeBreak", NULL, false, 32},
  { "TreeExplode", NULL, false, 32},
  { "SuitofArmorBreak", NULL, false, 32},
  { "PoisonShroomPain", NULL, false, 20},
  { "PoisonShroomDeath", NULL, false, 32},
  { "Ambient1", NULL, false, 1},
  { "Ambient2", NULL, false, 1},
  { "Ambient3", NULL, false, 1},
  { "Ambient4", NULL, false, 1},
  { "Ambient5", NULL, false, 1},
  { "Ambient6", NULL, false, 1},
  { "Ambient7", NULL, false, 1},
  { "Ambient8", NULL, false, 1},
  { "Ambient9", NULL, false, 1},
  { "Ambient10", NULL, false, 1},
  { "Ambient11", NULL, false, 1},
  { "Ambient12", NULL, false, 1},
  { "Ambient13", NULL, false, 1},
  { "Ambient14", NULL, false, 1},
  { "Ambient15", NULL, false, 1},
  { "StartupTick", NULL, false, 32},
  { "SwitchOtherLevel", NULL, false, 32},
  { "Respawn", NULL, false, 32},
  { "KoraxVoiceGreetings", NULL, true, 512},
  { "KoraxVoiceReady", NULL, true, 512},
  { "KoraxVoiceBlood", NULL, true, 512},
  { "KoraxVoiceGame", NULL, true, 512},
  { "KoraxVoiceBoard", NULL, true, 512},
  { "KoraxVoiceWorship", NULL, true, 512},
  { "KoraxVoiceMaybe", NULL, true, 512},
  { "KoraxVoiceStrong", NULL, true, 512},
  { "KoraxVoiceFace", NULL, true, 512},
  { "BatScream", NULL, false, 32},
  { "Chat", NULL, false, 512},
  { "MenuMove", NULL, false, 32},
  { "ClockTick", NULL, false, 32},
  { "Fireball", NULL, false, 32},
  { "PuppyBeat", NULL, false, 30},
  { "MysticIncant", NULL, false, 32}
};
